name: CommandButtons
version: '${project.version}'
main: dev.demeng.commandbuttons.CommandButtons
api-version: 1.13
authors: [ Demeng ]
description: Execute commands on block interaction.
website: https://demeng.dev/
softdepend: [ Vault ]
